@ProjetoAPI01_HostAddress=http://localhost:5034


POST {{ProjetoAPI01_HostAddress}}/api/usuarios/login
Content-Type: application/json
Accept: application/json

{
"email": "felipe1@aluno.senaisp.br",
"senha": "F1c"
}
###
